version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Taipei
    target-branch: master
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps(python)

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Taipei
    target-branch: master
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: deps(actions)
